#!/bin/sh

PADDING=128
THEME=breeze
TITLE='pcall.js'
LANG='javascript'

URL="https://ray.so/#language=${LANG}&theme=${THEME}&padding=${PADDING}&title=${TITLE}"


find .github/assets \
  -type f \
  -name 'use-*.js' \
  -fprint0 "%p" \
  -exec printf "\n\n ${URL}&code=%s" \; \
  -exec base64 -w0 {} \;

echo
