#!/bin/sh

PADDING=128
THEME=breeze
TITLE='pcall.js'
LANG='javascript'

URL="https://ray.so/#language=${LANG}&theme=${THEME}&padding=${PADDING}&title=${TITLE}"

# CMD='chromium'
find examples -type f -name 'simple.js' -exec base64 -w0 {} \; | xargs -0 printf "--app='${URL}&code=%s'" | xargs chromium

#xsel --input --clipboard --trim
# while read -r L; do
#   echo "L $L"
# done < <(find examples -type f -name '*simple.js')
