name: npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm test
      - run: npx unbuild
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.node_auth_token}}
